import { z } from "zod"
import { registry, ErrorResponseSchema } from "../docs/openapi"

// Helpers
const jsonResponse = (schema: any, description: string) => ({
  description,
  content: { "application/json": { schema } },
})

// Webhook Payload Schema
export const EmailWebhookPayloadSchema = registry.register(
  "EmailWebhookPayload",
  z.object({
    to: z
      .string()
      .email("Email người nhận không hợp lệ")
      .openapi({ example: "user@example.com", description: "Recipient email address" }),
    subject: z
      .string()
      .min(1, "Tiêu đề email là bắt buộc")
      .openapi({ example: "Kích Hoạt Tài Khoản — Bếp Phương", description: "Email subject" }),
    html: z
      .string()
      .min(1, "Nội dung email là bắt buộc")
      .openapi({ example: "<p>Nội dung email</p>", description: "Email HTML body content" }),
    from: z
      .string()
      .optional()
      .openapi({
        example: '"Bếp Phương" <noreply@bepphuong.online>',
        description: "Optional sender identity",
      }),
  })
)

// Response Schema for Webhook
export const EmailWebhookResponseSchema = registry.register(
  "EmailWebhookResponse",
  z.object({
    success: z.boolean().openapi({ example: true }),
    message: z.string().openapi({ example: "Email sent successfully" }),
  })
)

// Register OpenAPI Path: POST /webhooks/qstash/mail
registry.registerPath({
  method: "post",
  path: "/webhooks/qstash/mail",
  tags: ["Webhooks"],
  summary: "QStash Mail Worker Webhook",
  description:
    "Webhook endpoint invoked by Upstash QStash queue to deliver queued emails asynchronously via Resend.",
  request: {
    headers: z.object({
      "upstash-signature": z.string().optional().openapi({
        description: "HMAC signature generated by Upstash QStash for payload verification",
        example: "ey...",
      }),
    }),
    body: {
      content: {
        "application/json": {
          schema: EmailWebhookPayloadSchema,
        },
      },
    },
  },
  responses: {
    200: jsonResponse(EmailWebhookResponseSchema, "Email sent successfully"),
    400: jsonResponse(ErrorResponseSchema, "Invalid email payload"),
    401: jsonResponse(ErrorResponseSchema, "Missing or invalid QStash signature"),
    500: jsonResponse(
      ErrorResponseSchema,
      "Internal server error sending email (triggers QStash automatic retry)"
    ),
  },
})
